### ISSUE TITLE
salt[] as Salt module functions vs __salt__

### ISSUE THREAD

**Issue by Sylvain303** [bbinet/pillarstack#13]
EDIT:

```
salt --versions-report
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4 
```

you said:

`__salt__`: a dictionary of Salt module functions, useful so you  don't have to duplicate functions that already exist (note: runs on the master)

As seen here:
https://github.com/bbinet/pillarstack/blob/master/stack.py#L46

Does it allow, in jinja?

``` jinja
{%- for name, client in __salt__['pillar.get']('wsf:customers', {}).items() %}
```

gives nothing.

This one works

``` jinja
{%- for name, client in pillar['wsf']['customers'].items() %}
```

**Comment by bbinet** [comment]
I guess this is because the pillar data is just being built, so it is not available to the `__salt__` function yet.

We could add a function similar to `pillar.get` and make it available in the template so that it's easier to get the current state of the pillar or stack data.

**Comment by Sylvain303** [comment]
OK, I'm not enough in salt code to feel the difference. ;)

Could we reuse the `pillar.get` code to avoid duplicate?

I gonna try to paste some similar code into stack.py…
Thanks for the suggestion.

**Comment by bbinet** [comment]
I think, you just need to expose the function `salt.utils.traverse_dict_and_list` in the jinja template.

**Comment by Sylvain303** [comment]
OK [`salt.utils.traverse_dict_and_list`](https://github.com/saltstack/salt/blob/2015.8/salt/utils/__init__.py#L1460) seems good. I'll try that. 

Notice that I attached the ipython to your code following this [doc](https://docs.saltstack.com/en/latest/topics/development/modular_systems.html#interactive-debugging), before [line 52](https://github.com/bbinet/pillarstack/blob/master/stack.py#L53) and it outputed:

```
In [1]: __salt__['pillar.get']
Out[26]: <function salt.loaded.int.module.pillar.get>
```

I don't know what it is yet.

**Comment by bbinet** [comment]
Thanks, I didn't know about IPython debugging tool, that is useful.

**Comment by Sylvain303** [comment]
I'm beginning, so if you know some nice way to debug salt ext_pillar share it too. ;)

Because I often get in the master log:

```
[salt.pillar      ][CRITICAL][10580] Specified ext_pillar interface stack is unavailable
```

Which probably means that the code is wrong…

**Comment by bbinet** [comment]
It seems salt can't find the PillarStack ext_pillar module.
You should either use the new salt version 2016.3 in which PillarStack comes preinstalled, or you should follow installation guide on the readme to setup PillarStack for your current salt version:
https://github.com/bbinet/pillarstack#installation

**Comment by Sylvain303** [comment]
was python error… starting `salt-master -l debug` show the missing `import` now, it's ok… :)

See my fix, could it be done that way or is it ugly?

**Comment by bbinet** [comment]
We should not override the `__salt__['pillar.get']` function, because only salt itself is responsible for providing the module functions in the `__salt__` special variable, and it could potentially create some bad side effects.
Instead we could add a special `__stack__` variable in which we expose our custom functions that we'd like to be available in the jinja templates. So you can then create your `__stack__['pillar.get']` function or even better , a generic `__stack__['traverse']` function which is able to traverse both pillar or stack data.

I'm even wondering if it makes sense to allow traversing the `pillar` data: why not restrict the `traverse` function to the `stack` data only, as the `stack` data is originally initialized by copying the `pillar` data. What do you think? What is your own use case?

**Comment by Sylvain303** [comment]
OK, that what I was suspected. I will post my use case in my forked version, I'm testing a new approach too not using `ext_pillar` at all. That I would like to compare too.

I saw `traverse` you produced at [line 19](https://github.com/bbinet/pillarstack/blob/master/stack.py#L19), but as far that I understand the `traverse` dict isn't available inside [rendering loop](https://github.com/bbinet/pillarstack/blob/master/stack.py#L56), right?

Here's a sample of a highest level pillar description that I want to accomplish, more on that in my usecase description later:

``` yaml
# top level pillar customer abstract config.
# Status: Prototype, not functional 
#
# See customers.d/ for details on each customer
# See also: base/customers/init.sls for state.
# 
#
wsf:
  customers:
    # list elements will be used for naming users (shell, db)
    client1:
      domain-name: client1-domain.fr
      enabled: true 
      delete: false
      # service to configure for this customer
      services:
        - webhost
        - dns
        - mysql
        - sftp
      # some service override…
      override:
        user-shell:
          name: test
        php-fpm:
          user:
            name: test
            group: test
          pool:
            pm: dynamic
            pm.max_children: 7
            pm.start_servers: 3
            pm.min_spare_servers: 1
            pm.max_spare_servers: 3
            pm.process_idle_timeout: 30s
            pm.max_requests: 100
    # client2 as more default values
    client2:
      domain-name: more-domain.com
      enabled: true
      delete: false
      services:
        - webhost
        - dns
    client3:
      domain-name: somedomain.fr
      enabled: true
      # default, delete: false
      services:
        - webhost
        - dns
        - db
        - sftp
```

As you may guess (or not) it is intended to generate more lower level pillar config for each specific services… I'm currently working on generating mysql/mariaDB pillar for configuring the database service.

I was trying to produce a jinja template which in turn would generate some mysql pillar config from this higher level description…

I stop here, because my use case goes far deeper than the current access to loaded pillar data inside this ext_pillar via `__salt__['pillar.get']('wsf:customers', {}).items()`
