### ISSUE TITLE
My merging strategies don't work

### ISSUE THREAD

**Issue by mjinks** [bbinet/pillarstack#14]
I need to merge two data sources into a single pillar, which is what brings me to PillarStack. But I'm misunderstanding something.

If I have, in a .yml file, call it '/srv/exe-pillar/first.yml', something like:

```
users:
  user-foo:
    home: /home/foo
  user-bar:
    home: /home/bar
```

...alongside another one, say, '/srv/exe-pillar/second.yml':

```
users:
  user-foo:
    shell: /bin/bash
  user-bar:
    shell: /bin/false
```

...listed in '/srv/ext_pillar/stack.cfg' as:

```
stack/first.yml
stack/second.yml
```

That works fine. But if I augment one of the pillar files with a merge strategy, like:

```
users:
  _: merge_last
  user-foo:
    home: /home/foo
 [...]
```

...the result fails to compile, with Jinja errors, for example:

```
----------
    Rendering SLS 'base:users' failed: Jinja variable 'str object' has no attribute 'get'
----------
```

So I guess I'm misunderstanding something that should be obvious?  I need to be able to guarantee that my sub-pillars render in a specified order; is there a different way I should be coming at this?

Thanks.
