### ISSUE TITLE
Pillar render error: Failed to load ext_pillar stack: Encountered unknown tag 'import_yaml'

### ISSUE THREAD

**Issue by Sylvain303** [bbinet/pillarstack#15]
following #13 use case I presented [here](https://github.com/opensource-expert/pillarstack/tree/use-case/use_case).

Importing [mysql_users.sls](https://github.com/opensource-expert/pillarstack/blob/use-case/use_case/state/customers/templates/mysql_users.sls) as a pillarstack source raise this error:

Which becomes:

``` yaml
# vim: set ft=jinja:
{# will import on the pillar side a generated passwords database -#}
{% import_yaml "/srv/salt/pillar/auto/managed_password.yaml" as pass with context %}
mysql:
  # Managed mariaDB users for customers
  user:
{% set db_server = 'localhost' -%}
{%- for name, prop in __stack__['traverse'](pillar, 'wsf:customers', {}).items() %}
    {{ name }}:
      password: {{ '"{{' }} pass['{{ name }}']['mysql'] {{ '}}"' }}
      hosts:
        - {{ db_server }}
      databases:
        - database: {{ name }}
          grants: ['all privileges']
{% endfor -%}
```

on `salt-master -ldebug`

```
[CRITICAL] Pillar render error: Failed to load ext_pillar stack: Encountered unknown tag 'import_yaml'.
```

what subset of jinja renderer is actually supported?

The goal here is to have mysql (customers) passwords handled outside and possibly shared, with other state.

tested with: modified stack.py, ([stack-traverse](https://github.com/bbinet/pillarstack/tree/stack-traverse) https://github.com/opensource-expert/pillarstack/commit/5ecc7c03d5a493c792fe3e2df77a271820ceea60)

```
salt --versions-report 
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4 
```
