### ISSUE TITLE
Support for locating pillarstack tree on GitFS

### ISSUE THREAD

**Issue by khaije1** [bbinet/pillarstack#16]
I'm currently using gitfs-backed ext_pillar and have come to realize the importance of the functionality that pillarstack provides.

Is it possible to preserve the current advantages of a change-controlled pillar while using pillarstack?

To illustrate, my hope is for support for something like this (altered from documentation):

```
ext_pillar:
  - stack:
      pillar:environment:
        dev: git://git@github.com/example/pillar.git:/path/to/dev/stack.cfg
```
# or

```
        prod: 
          - uri: git://git@github.com/example/pillar.git
          - branch: master
          - subtree_uri: /path/to/prod/stack.cfg
```

Thanks for this project!
