### ISSUE TITLE
Pillarenv targeting is not working

### ISSUE THREAD

**Issue by Slemaire-PNI** [bbinet/pillarstack#56]
Apologies if I've misunderstood the docs, but in the readme, this example is given:

 ```
ext_pillar:
   - stack:
       pillar:environment:
         dev: /path/to/dev/stack.cfg
         prod: /path/to/prod/stack.cfg
```

However, using this exact configuration below,

```
 ext_pillar:
   - stack:
       pillar:environment:
         dev: /srv/pillar/dev/stack.cfg
         master: /srv/pillar/master/stack.cfg
```

Config files don't load.  Notable things about our environment are pillarenv_from_saltenv is true, and everything is running python3.  When not using pillar:environment:, everything works as expected.
